"""RC2 Sprint 3 — Semantic Pattern Registry

Single source of truth for all Sprint 3 semantic patterns.
This module exposes the 74-pattern definitions and category distribution
without duplicating the runtime or build logic.
"""

from collections import Counter
from datetime import datetime
from typing import List, Dict, Any, Tuple


SPRINT3_PATTERN_DEFINITIONS: List[Dict[str, Any]] = [
    # THEMES (20 patterns)
    {
        'id': 'theme_adventure',
        'name': 'Adventure',
        'category': 'theme',
        'description': 'Journey, exploration, discovery, quest',
        'keywords': ['macera', 'yolculuk', 'keşif', 'sefaret', 'arama', 'deniz', 'dağ'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.5,
        'confidence_weight': 1.0,
        'status': 'VALIDATED',
    },
    {
        'id': 'theme_growth',
        'name': 'Growth & Development',
        'category': 'theme',
        'description': 'Personal development, learning, maturation',
        'keywords': ['büyüme', 'gelişim', 'olgunlaşma', 'öğrenme', 'değişme', 'ilerleme'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.6,
        'confidence_weight': 0.95,
        'status': 'VALIDATED',
    },
    {
        'id': 'theme_conflict',
        'name': 'Conflict & Challenge',
        'category': 'theme',
        'description': 'Struggle, confrontation, combat, obstacles',
        'keywords': ['çatışma', 'mücadele', 'savaş', 'karşılaşma', 'engel', 'zorluk'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.4,
        'confidence_weight': 1.0,
        'status': 'VALIDATED',
    },
    {
        'id': 'theme_friendship',
        'name': 'Friendship & Connection',
        'category': 'theme',
        'description': 'Bonds, collaboration, loyalty, partnership',
        'keywords': ['dostluk', 'arkadaşlık', 'birlik', 'dayanışma', 'sadakat', 'yardım'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.5,
        'confidence_weight': 1.0,
        'status': 'VALIDATED',
    },
    {
        'id': 'theme_family',
        'name': 'Family & Kinship',
        'category': 'theme',
        'description': 'Family relationships, parenthood, siblings',
        'keywords': ['aile', 'baba', 'anne', 'kardeş', 'ebeveyn', 'ata', 'nesil'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.3,
        'confidence_weight': 1.0,
        'status': 'VALIDATED',
    },
    {
        'id': 'theme_courage',
        'name': 'Courage & Bravery',
        'category': 'theme',
        'description': 'Bravery, fearlessness, heroism, confidence',
        'keywords': ['cesaret', 'yiğitlik', 'korkmamak', 'kahraman', 'güven', 'cüret'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.5,
        'confidence_weight': 0.95,
        'status': 'VALIDATED',
    },
    {
        'id': 'theme_knowledge',
        'name': 'Learning & Wisdom',
        'category': 'theme',
        'description': 'Education, discovery of knowledge, wisdom',
        'keywords': ['bilgi', 'çalışma', 'eğitim', 'öğrenme', 'keşfet', 'akıl'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.4,
        'confidence_weight': 0.9,
        'status': 'VALIDATED',
    },
    {
        'id': 'theme_mystery',
        'name': 'Mystery & Intrigue',
        'category': 'theme',
        'description': 'Puzzle, secret, investigation, suspense',
        'keywords': ['gizem', 'sır', 'araştırma', 'ipucu', 'belirsizlik', 'merak'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.3,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'theme_wonder',
        'name': 'Wonder & Magic',
        'category': 'theme',
        'description': 'Magic, fantasy, supernatural, extraordinary',
        'keywords': ['sihir', 'büyü', 'harika', 'doğaüstü', 'mucize', 'fantezi'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.4,
        'confidence_weight': 0.9,
        'status': 'NEW',
    },
    {
        'id': 'theme_loss',
        'name': 'Loss & Grief',
        'category': 'theme',
        'description': 'Sadness, grief, farewell, goodbye',
        'keywords': ['kayıp', 'yas', 'acı', 'veda', 'ayrılık', 'hüzün'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'theme_belonging',
        'name': 'Belonging & Acceptance',
        'category': 'theme',
        'description': 'Inclusion, acceptance, finding home',
        'keywords': ['ait olma', 'kabul', 'ev', 'toplum', 'aidiyet', 'yer'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.3,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'theme_justice',
        'name': 'Justice & Fairness',
        'category': 'theme',
        'description': 'Right vs wrong, morality, balance',
        'keywords': ['adalet', 'doğru', 'hak', 'yanlış', 'ceza', 'ödül'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.3,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'theme_nature',
        'name': 'Nature & Environment',
        'category': 'theme',
        'description': 'Natural world, environment, animals',
        'keywords': ['doğa', 'çevre', 'hayvan', 'mevsim', 'orman', 'su'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.4,
        'confidence_weight': 0.9,
        'status': 'NEW',
    },
    {
        'id': 'theme_identity',
        'name': 'Identity & Self-Discovery',
        'category': 'theme',
        'description': 'Who am I, self-realization',
        'keywords': ['kimlik', 'öz', 'yüz', 'ben', 'tanıma', 'bilinç'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.3,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'theme_dreams',
        'name': 'Dreams & Aspiration',
        'category': 'theme',
        'description': 'Goals, wishes, aspirations, ambition',
        'keywords': ['rüya', 'hayal', 'hedef', 'isteme', 'tutkun', 'imren'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.3,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'theme_tradition',
        'name': 'Tradition & Culture',
        'category': 'theme',
        'description': 'Customs, heritage, cultural values',
        'keywords': ['gelenek', 'kültür', 'miras', 'görenek', 'değer', 'adet'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.3,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'theme_change',
        'name': 'Change & Adaptation',
        'category': 'theme',
        'description': 'Transformation, adaptation, new beginning',
        'keywords': ['değişim', 'uyum', 'başlangıç', 'yeni', 'devrim', 'dönüş'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.4,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'theme_power',
        'name': 'Power & Authority',
        'category': 'theme',
        'description': 'Leadership, influence, control, strength',
        'keywords': ['güç', 'yetki', 'kontrol', 'liderlik', 'etki', 'kuvvet'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.3,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'theme_freedom',
        'name': 'Freedom & Liberation',
        'category': 'theme',
        'description': 'Liberty, independence, breaking free',
        'keywords': ['özgürlük', 'bağımsızlık', 'kurtulma', 'baskıdan kurtulma'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.3,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'theme_redemption',
        'name': 'Redemption & Renewal',
        'category': 'theme',
        'description': 'Transformation, second chances, amends',
        'keywords': ['kurtarma', 'iyileşme', 'bağışlama', 'yenileme', 'tövbe'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    # CHARACTER ROLES (12 patterns)
    {
        'id': 'character_protagonist',
        'name': 'Protagonist',
        'category': 'character_role',
        'description': 'Main character, hero, central figure',
        'keywords': ['ana karakter', 'kahraman', 'çocuk', 'kız', 'oğlan', 'başkarakter'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'low',
        'expected_density': 0.6,
        'confidence_weight': 1.0,
        'status': 'VALIDATED',
    },
    {
        'id': 'character_antagonist',
        'name': 'Antagonist',
        'category': 'character_role',
        'description': 'Opposition, villain, opposing force',
        'keywords': ['düşman', 'kötü', 'olumsuz', 'karşı', 'muhalif'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'high',
        'expected_density': 0.1,
        'confidence_weight': 0.7,
        'status': 'VALIDATED',
    },
    {
        'id': 'character_mentor',
        'name': 'Mentor & Guide',
        'category': 'character_role',
        'description': 'Teacher, guide, wise figure, advisor',
        'keywords': ['öğretmen', 'rehber', 'bilge', 'yaşlı', 'danışman', 'öncü'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'low',
        'expected_density': 0.3,
        'confidence_weight': 0.9,
        'status': 'VALIDATED',
    },
    {
        'id': 'character_companion',
        'name': 'Companion & Friend',
        'category': 'character_role',
        'description': 'Ally, friend, partner, helper',
        'keywords': ['arkadaş', 'dost', 'yoldaş', 'asistan', 'müttefik', 'yardımcı'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'low',
        'expected_density': 0.4,
        'confidence_weight': 1.0,
        'status': 'VALIDATED',
    },
    {
        'id': 'character_innocent',
        'name': 'Innocent & Victim',
        'category': 'character_role',
        'description': 'Innocent party, victim, vulnerable',
        'keywords': ['masum', 'kurban', 'çaresiz', 'zayıf', 'savunmasız', 'mağdur'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'high',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'character_trickster',
        'name': 'Trickster & Deceiver',
        'category': 'character_role',
        'description': 'Cunning, deceiver, prankster',
        'keywords': ['aldatıcı', 'hile', 'oyun', 'sinsi', 'hilekâr', 'üretici'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'high',
        'expected_density': 0.2,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'character_sage',
        'name': 'Sage & Wise One',
        'category': 'character_role',
        'description': 'Wise figure, oracle, philosopher',
        'keywords': ['bilge', 'usta', 'danışman', 'dergah', 'fen', 'hikmet'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'character_comic_relief',
        'name': 'Comic Relief & Jester',
        'category': 'character_role',
        'description': 'Humorous, entertainer, buffoon',
        'keywords': ['komik', 'espri', 'şaka', 'eğlence', 'buffo', 'maskara'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.7,
        'status': 'NEW',
    },
    {
        'id': 'character_creature',
        'name': 'Creature & Animal',
        'category': 'character_role',
        'description': 'Animal companion, magical creature',
        'keywords': ['hayvan', 'canlı', 'yaratık', 'varlık', 'elf', 'yoksa'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'medium',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'character_outsider',
        'name': 'Outsider & Outcast',
        'category': 'character_role',
        'description': 'Outcast, outsider, misfit',
        'keywords': ['dışlanmış', 'misfit', 'garip', 'yadığı', 'paria', 'yabancı'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'character_authority',
        'name': 'Authority Figure',
        'category': 'character_role',
        'description': 'Figure in power, ruler, leader',
        'keywords': ['yetkilisi', 'hakim', 'kral', 'prenses', 'başkan', 'sahibi'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'character_observer',
        'name': 'Observer & Narrator',
        'category': 'character_role',
        'description': 'Witness, observer, narrator',
        'keywords': ['gözlemci', 'tanık', 'anlatıcı', 'bakış', 'perspektif'],
        'matching_strategy': 'contextual',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.7,
        'status': 'NEW',
    },
    # LEARNING OUTCOMES (12 patterns)
    {
        'id': 'learning_cognitive',
        'name': 'Cognitive Learning',
        'category': 'learning_outcome',
        'description': 'Knowledge, understanding, critical thinking',
        'keywords': ['öğrendi', 'anladı', 'bildi', 'kavradı', 'düşün', 'akıl'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'low',
        'expected_density': 0.4,
        'confidence_weight': 0.9,
        'status': 'VALIDATED',
    },
    {
        'id': 'learning_social',
        'name': 'Social Learning',
        'category': 'learning_outcome',
        'description': 'Cooperation, communication, interpersonal',
        'keywords': ['işbirliği', 'dayanışma', 'iletişim', 'empati', 'konuş', 'dinle'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'high',
        'expected_density': 0.3,
        'confidence_weight': 0.85,
        'status': 'VALIDATED',
    },
    {
        'id': 'learning_emotional',
        'name': 'Emotional Learning',
        'category': 'learning_outcome',
        'description': 'Emotional intelligence, self-awareness',
        'keywords': ['hissetti', 'duygulanıyor', 'deneyimle', 'anlış', 'duygu', 'kalp'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'high',
        'expected_density': 0.3,
        'confidence_weight': 0.8,
        'status': 'VALIDATED',
    },
    {
        'id': 'learning_physical',
        'name': 'Physical Learning',
        'category': 'learning_outcome',
        'description': 'Motor skills, physical activity, movement',
        'keywords': ['hareketi', 'aktivite', 'oyun', 'spor', 'dans', 'koşu'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.85,
        'status': 'VALIDATED',
    },
    {
        'id': 'learning_moral',
        'name': 'Moral Learning',
        'category': 'learning_outcome',
        'description': 'Ethics, right vs wrong, moral reasoning',
        'keywords': ['ahlak', 'doğru', 'hak', 'yanlış', 'etik', 'vicdan'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'high',
        'expected_density': 0.25,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'learning_creativity',
        'name': 'Creative Learning',
        'category': 'learning_outcome',
        'description': 'Imagination, creativity, innovation',
        'keywords': ['yaratıcılık', 'hayal', 'sanat', 'müzik', 'icat', 'buluş'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'medium',
        'expected_density': 0.25,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'learning_resilience',
        'name': 'Resilience & Perseverance',
        'category': 'learning_outcome',
        'description': 'Perseverance, determination',
        'keywords': ['ısrarcı', 'azim', 'yılmamak', 'zorluğa katlansa', 'tekrar'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'medium',
        'expected_density': 0.25,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'learning_cultural',
        'name': 'Cultural Learning',
        'category': 'learning_outcome',
        'description': 'Cultural awareness, understanding diversity',
        'keywords': ['kültür', 'farklılık', 'gelenek', 'adet', 'ırk', 'din'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'learning_environmental',
        'name': 'Environmental Awareness',
        'category': 'learning_outcome',
        'description': 'Ecological, care for nature',
        'keywords': ['çevre', 'doğa', 'koruma', 'yaşam', 'ağaç', 'hayvan'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'learning_critical_thinking',
        'name': 'Critical Thinking',
        'category': 'learning_outcome',
        'description': 'Analysis, evaluation, questioning',
        'keywords': ['analiz', 'değerlend', 'sorgula', 'neden', 'nasıl', 'kanıt'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'high',
        'expected_density': 0.2,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'learning_self_awareness',
        'name': 'Self-Awareness & Reflection',
        'category': 'learning_outcome',
        'description': 'Self-knowledge, reflection',
        'keywords': ['kendini tanı', 'iç denetim', 'farkında', 'yansıt', 'keşfet'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'learning_problem_solving',
        'name': 'Problem-Solving',
        'category': 'learning_outcome',
        'description': 'Solution finding, strategy, planning',
        'keywords': ['çöz', 'plan', 'strateji', 'çare', 'sonuç', 'çıkış'],
        'matching_strategy': 'context_window',
        'default_fp_risk': 'medium',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    # CONFLICTS (10 patterns)
    {
        'id': 'conflict_man_vs_self',
        'name': 'Man vs Self',
        'category': 'conflict',
        'description': 'Internal struggle, personal challenge',
        'keywords': ['iç çatışma', 'kendisi', 'tercih', 'ikilem', 'karar', 'vicdan'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'conflict_man_vs_man',
        'name': 'Man vs Man',
        'category': 'conflict',
        'description': 'Interpersonal conflict, competition',
        'keywords': ['çatışma', 'rakip', 'düşman', 'dövüş', 'anlaşmazlık', 'çekişme'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.3,
        'confidence_weight': 0.9,
        'status': 'NEW',
    },
    {
        'id': 'conflict_man_vs_nature',
        'name': 'Man vs Nature',
        'category': 'conflict',
        'description': 'Struggle against natural forces',
        'keywords': ['doğa', 'fırtına', 'sel', 'deprem', 'soğuk', 'hayvan'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'conflict_man_vs_society',
        'name': 'Man vs Society',
        'category': 'conflict',
        'description': 'Social conflict, rebellion',
        'keywords': ['toplum', 'haksızlık', 'isyan', 'otorite', 'kanun', 'sistem'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'conflict_man_vs_fate',
        'name': 'Man vs Fate',
        'category': 'conflict',
        'description': 'Struggle against destiny',
        'keywords': ['kader', 'talih', 'yazı', 'tesadüf', 'ölüm', 'çok geç'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'conflict_ideological',
        'name': 'Ideological Conflict',
        'category': 'conflict',
        'description': 'Conflict of beliefs, values',
        'keywords': ['inanç', 'felsefe', 'değer', 'doğru', 'yanlış', 'ideoloji'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'conflict_economic',
        'name': 'Economic Conflict',
        'category': 'conflict',
        'description': 'Conflict over resources, money',
        'keywords': ['para', 'zengin', 'fakir', 'kıtlık', 'bolluk', 'miras'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'conflict_political',
        'name': 'Political Conflict',
        'category': 'conflict',
        'description': 'Power struggles, governance',
        'keywords': ['hükümet', 'kral', 'prenses', 'savaş', 'taht', 'yönetim'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'low',
        'expected_density': 0.15,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'conflict_romantic',
        'name': 'Romantic Conflict',
        'category': 'conflict',
        'description': 'Love triangles, relationship challenges',
        'keywords': ['aşk', 'sevgi', 'kalp', 'evlilik', 'seçim', 'ayrılık'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'conflict_generational',
        'name': 'Generational Conflict',
        'category': 'conflict',
        'description': 'Youth vs age, tradition vs change',
        'keywords': ['kuşak', 'genç', 'yaşlı', 'gelenek', 'modern', 'farklılık'],
        'matching_strategy': 'keyword_frequency',
        'default_fp_risk': 'medium',
        'expected_density': 0.15,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    # EMOTIONS (12 patterns)
    {
        'id': 'emotion_joy',
        'name': 'Joy & Happiness',
        'category': 'emotion',
        'description': 'Happiness, delight, contentment',
        'keywords': ['mutluluk', 'sevinç', 'gül', 'kutlama', 'coşku', 'keyif'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'low',
        'expected_density': 0.3,
        'confidence_weight': 0.9,
        'status': 'NEW',
    },
    {
        'id': 'emotion_sadness',
        'name': 'Sadness & Sorrow',
        'category': 'emotion',
        'description': 'Sadness, grief, melancholy, despair',
        'keywords': ['hüzün', 'keder', 'ağla', 'acı', 'üzüntü', 'mutsuzluk'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.9,
        'status': 'NEW',
    },
    {
        'id': 'emotion_fear',
        'name': 'Fear & Anxiety',
        'category': 'emotion',
        'description': 'Fear, anxiety, worry, terror',
        'keywords': ['korku', 'kaygı', 'endişe', 'dehşet', 'ürkü', 'çekince'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.9,
        'status': 'NEW',
    },
    {
        'id': 'emotion_anger',
        'name': 'Anger & Rage',
        'category': 'emotion',
        'description': 'Anger, rage, fury, frustration',
        'keywords': ['öfke', 'gazap', 'kızgınlık', 'hiddet', 'sinir', 'nefret'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'low',
        'expected_density': 0.2,
        'confidence_weight': 0.9,
        'status': 'NEW',
    },
    {
        'id': 'emotion_love',
        'name': 'Love & Affection',
        'category': 'emotion',
        'description': 'Love, affection, tenderness, care',
        'keywords': ['aşk', 'sevgi', 'ten', 'bakım', 'şefkat', 'hubb'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.2,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'emotion_surprise',
        'name': 'Surprise & Wonder',
        'category': 'emotion',
        'description': 'Surprise, astonishment, amazement',
        'keywords': ['sürpriz', 'hayret', 'şaşkınlık', 'mucize', 'merak'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'emotion_shame',
        'name': 'Shame & Embarrassment',
        'category': 'emotion',
        'description': 'Shame, embarrassment, guilt',
        'keywords': ['utanç', 'pişmanlık', 'suçlu', 'alçaklık', 'eziyet'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.1,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'emotion_hope',
        'name': 'Hope & Optimism',
        'category': 'emotion',
        'description': 'Hope, optimism, belief, expectation',
        'keywords': ['umut', 'iyimserlik', 'inanç', 'beklenti', 'gelecek'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'emotion_despair',
        'name': 'Despair & Hopelessness',
        'category': 'emotion',
        'description': 'Despair, hopelessness, defeat',
        'keywords': ['çaresizlik', 'ümitsizlik', 'yenilgi', 'teslim', 'bitti'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.1,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'emotion_trust',
        'name': 'Trust & Confidence',
        'category': 'emotion',
        'description': 'Trust, confidence, faith in others',
        'keywords': ['güven', 'inanç', 'sadakat', 'dürüstlük', 'vefa'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'emotion_betrayal',
        'name': 'Betrayal & Distrust',
        'category': 'emotion',
        'description': 'Betrayal, distrust, disappointment',
        'keywords': ['ihanet', 'terketme', 'aldatma', 'güvensizlik', 'hayal kırıklığı'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.1,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'emotion_pride',
        'name': 'Pride & Dignity',
        'category': 'emotion',
        'description': 'Pride, dignity, self-respect, arrogance',
        'keywords': ['gurur', 'saygınlık', 'kibir', 'onur', 'izzet'],
        'matching_strategy': 'sentiment',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    # NARRATIVE STRUCTURES (8 patterns)
    {
        'id': 'narrative_linear',
        'name': 'Linear Narrative',
        'category': 'narrative_structure',
        'description': 'Straightforward chronological progression',
        'keywords': ['sonra', 'sonunda', 'daha sonra', 'şimdi', 'ilk', 'son'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'low',
        'expected_density': 0.4,
        'confidence_weight': 0.85,
        'status': 'NEW',
    },
    {
        'id': 'narrative_flashback',
        'name': 'Flashback & Memory',
        'category': 'narrative_structure',
        'description': 'Past events through flashback',
        'keywords': ['hatırla', 'geçmişte', 'uzun zaman', 'geçen', 'anı', 'iyi eski'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'medium',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'narrative_parallel',
        'name': 'Parallel Narratives',
        'category': 'narrative_structure',
        'description': 'Multiple storylines in parallel',
        'keywords': ['eş zamanlı', 'aynı anda', 'başka', 'diğeri', 'ikinci', 'ayrıntı'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'narrative_frame',
        'name': 'Frame Narrative',
        'category': 'narrative_structure',
        'description': 'Story within a story',
        'keywords': ['hikaye anlat', 'tanık', 'öykü', 'anlatma', 'böyle', 'derken'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'high',
        'expected_density': 0.15,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
    {
        'id': 'narrative_plot_twist',
        'name': 'Plot Twist & Revelation',
        'category': 'narrative_structure',
        'description': 'Unexpected turn, revelations',
        'keywords': ['beklenti', 'sürpriz', 'açıklanmak', 'çok kötü', 'ne var ki'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'high',
        'expected_density': 0.1,
        'confidence_weight': 0.7,
        'status': 'NEW',
    },
    {
        'id': 'narrative_rising_action',
        'name': 'Rising Action & Tension',
        'category': 'narrative_structure',
        'description': 'Escalating tension',
        'keywords': ['kötüleşmek', 'artmak', 'endişe', 'sorun', 'çok zor', 'ciddi'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'medium',
        'expected_density': 0.2,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'narrative_climax',
        'name': 'Climax & Resolution',
        'category': 'narrative_structure',
        'description': 'Peak, conflict resolution',
        'keywords': ['doruk', 'çatışma', 'sonuç', 'çözüm', 'karar', 'bitir'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'medium',
        'expected_density': 0.15,
        'confidence_weight': 0.8,
        'status': 'NEW',
    },
    {
        'id': 'narrative_denouement',
        'name': 'Denouement & Reflection',
        'category': 'narrative_structure',
        'description': 'Falling action, reflection',
        'keywords': ['sonuncu', 'refleks', 'yansıt', 'anlamı', 'dernek', 'ilham'],
        'matching_strategy': 'structure',
        'default_fp_risk': 'high',
        'expected_density': 0.1,
        'confidence_weight': 0.75,
        'status': 'NEW',
    },
]


def get_sprint3_pattern_definitions() -> List[Dict[str, Any]]:
    return list(SPRINT3_PATTERN_DEFINITIONS)


def get_sprint3_pattern_count() -> int:
    return len(SPRINT3_PATTERN_DEFINITIONS)


def get_sprint3_category_distribution() -> Dict[str, int]:
    return dict(Counter(p['category'] for p in SPRINT3_PATTERN_DEFINITIONS))


def validate_sprint3_pattern_definitions() -> Tuple[bool, List[str]]:
    errors: List[str] = []
    required_keys = {
        'id', 'name', 'category', 'description', 'keywords',
        'matching_strategy', 'default_fp_risk', 'expected_density',
        'confidence_weight', 'status',
    }

    seen_ids = set()
    for idx, pattern in enumerate(SPRINT3_PATTERN_DEFINITIONS, start=1):
        missing = required_keys - pattern.keys()
        if missing:
            errors.append(f"Pattern {idx} missing keys: {sorted(missing)}")

        pattern_id = pattern.get('id')
        if not pattern_id:
            errors.append(f"Pattern {idx} has no id")
        elif pattern_id in seen_ids:
            errors.append(f"Duplicate pattern id: {pattern_id}")
        else:
            seen_ids.add(pattern_id)

    return len(errors) == 0, errors


def export_registry_to_json(filepath: str) -> bool:
    try:
        import json
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump({
                'timestamp': datetime.now().isoformat(),
                'total_patterns': get_sprint3_pattern_count(),
                'category_distribution': get_sprint3_category_distribution(),
                'patterns': SPRINT3_PATTERN_DEFINITIONS,
            }, f, indent=2, ensure_ascii=False)
        return True
    except Exception:
        return False
