#!/usr/bin/env python3
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_JSON = ROOT / 'artifact_inventory_audit.json'
OUT_MD = ROOT / 'artifact_inventory_audit.md'

files = []
for p in ROOT.rglob('*.json'):
    if any(part.startswith('.') for part in p.parts):
        continue
    name = p.name
    if re.search(r'\bphase|\brc', name, re.I):
        files.append(p)

report = {
    'scanned_files_count': len(files),
    'files': [],
    'verification_files': [],
    'benchmark_files': [],
    'nonstandard_naming': [],
    'verification_with_benchmark_content': [],
    'benchmark_with_verification_content': []
}

book_titles = ['Tavşan Pati', 'Büyülü Yastıklar', 'Benim Adım Kristof Kolomb']

for p in sorted(files):
    try:
        text = p.read_text(encoding='utf-8')
        data = json.loads(text)
    except Exception as e:
        data = None
    name = p.name
    lower = name.lower()
    classification_by_name = 'unknown'
    if 'verification' in lower or 'verific' in lower:
        classification_by_name = 'verification'
    if 'benchmark' in lower or 'results' in lower or 'endpoint_results' in lower:
        classification_by_name = 'benchmark'
    keys = list(data.keys()) if isinstance(data, dict) else []

    # content heuristics
    content_benchmark = False
    content_verification = False
    if isinstance(data, dict):
        if 'books' in data and isinstance(data['books'], dict):
            content_benchmark = True
        # benchmark-like keys
        for k in ['endpoints', 'pdf', 'word', 'teacher', 'performance', 'confidence', 'classification', 'books']:
            if k in keys:
                content_benchmark = True
        # verification-like keys
        for k in ['tests_run', 'pytest_command', 'results', 'checks', 'equal_without_shadow', 'deterministic', 'production_payload_unchanged', 'files_changed']:
            if k in keys:
                content_verification = True

    # nonstandard naming heuristics
    basename = p.stem
    nonstandard = False
    # if contains uppercase or spaces or book titles
    if any(ch.isupper() for ch in basename) or ' ' in basename or any(bt.lower() in name.lower() for bt in book_titles):
        nonstandard = True
    # if not matching expected pattern phaseNN..._feature_... or phaseNN..._...verification
    if not re.match(r'^phase\d+[a-z]?_', basename, re.I) and not re.match(r'^rc\d+', basename, re.I):
        # allow rc11_* files
        if not re.match(r'^rc\d+', basename, re.I):
            nonstandard = True

    entry = {
        'path': str(p.relative_to(ROOT)),
        'filename': name,
        'classification_by_name': classification_by_name,
        'top_level_keys': keys,
        'content_benchmark': content_benchmark,
        'content_verification': content_verification,
        'nonstandard_naming': nonstandard
    }
    report['files'].append(entry)
    if classification_by_name == 'verification':
        report['verification_files'].append(entry)
        if content_benchmark:
            report['verification_with_benchmark_content'].append(entry)
    if classification_by_name == 'benchmark':
        report['benchmark_files'].append(entry)
        if content_verification:
            report['benchmark_with_verification_content'].append(entry)
    if nonstandard:
        report['nonstandard_naming'].append(entry)

# write JSON
OUT_JSON.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')

# write markdown summary
lines = []
lines.append('# Artifact Inventory Audit')
lines.append('')
lines.append(f'Generated by script: scripts/artifact_inventory_audit.py')
lines.append('')
lines.append(f'**Scanned files**: {report["scanned_files_count"]}')
lines.append('')
lines.append('## Summary')
lines.append('')
lines.append(f'- Verification files detected (by name): {len(report["verification_files"])}')
lines.append(f'- Benchmark files detected (by name): {len(report["benchmark_files"])}')
lines.append(f'- Nonstandard named files: {len(report["nonstandard_naming"])}')
lines.append(f'- Verification files containing benchmark-like content: {len(report["verification_with_benchmark_content"]) }')
lines.append(f'- Benchmark files containing verification-like content: {len(report["benchmark_with_verification_content"]) }')
lines.append('')
lines.append('## Nonstandard Naming Examples')
for e in report['nonstandard_naming'][:20]:
    lines.append(f'- {e["path"]}')
lines.append('')
lines.append('## Verification files with embedded benchmark content')
for e in report['verification_with_benchmark_content'][:20]:
    lines.append(f'- {e["path"]} (keys: {e["top_level_keys"]})')
lines.append('')
lines.append('## Benchmark files with verification-like content')
for e in report['benchmark_with_verification_content'][:20]:
    lines.append(f'- {e["path"]} (keys: {e["top_level_keys"]})')

OUT_MD.write_text('\n'.join(lines), encoding='utf-8')
print('Wrote', OUT_JSON, OUT_MD)
