"""
Quality gate and consistency check key definitions.

These constants define gate names, log prefixes, and audit keys used in the
narrative analysis pipeline for ensuring report quality and book consistency.
"""

# Gate names
SUMMARY_PROOF_CONSISTENCY_GATE = "OZET_KANIT_TUTARLILIK_KAPISI"
BOOK_CONSISTENCY_CHECK_GATE = "KITAP_TUTARLILIK_DENETIMI"
ALT_KAPILAR = "alt_kapilar"
STOPPING_GATE_KEY = "durduran_kapi"
QUALITY_GATE_KEY = "kalite_kapisi"
REPORT_QUALITY_GATE_V6_CODE = "RAPOR_KALITE_KAPISI_V6"

# Log prefixes for consistency gates
SUMMARY_RENDER_GATE_LOG_PREFIX = "[SUMMARY_RENDER_GATE]"
BOOK_CONSISTENCY_CHECK_GATE_LOG_PREFIX = "[KITAP_TUTARLILIK_DENETIMI]"
REPORT_QUALITY_GATE_V7_WARNING_LOG_PREFIX = "[RAPOR_KALITE_KAPISI_V7_WARNING_ONLY]"
REPORT_QUALITY_GATE_V6_LOG_PREFIX = "[RAPOR_KALITE_KAPISI_V6]"

# Log prefixes for API instrumentation
APP_API_RAPOR_FRESH_VISUAL_SCAN_LOG_PREFIX = "[app.api_rapor] FRESH_VISUAL_SCAN"
APP_API_RAPOR_FRESH_VISUAL_SCAN_FAILED_LOG_PREFIX = "[app.api_rapor] FRESH_VISUAL_SCAN_FAILED"
APP_API_RAPOR_REQUEST_LOG_PREFIX = "[app.api_rapor] REQUEST"
APP_API_RAPOR_AFTER_KANIT_REVALIDATION_LOG_PREFIX = "[app.api_rapor] AFTER_KANIT_REVALIDATION"
APP_API_RAPOR_BLOCKED_BY_ANALYSIS_QUALITY_LOG_PREFIX = "[app.api_rapor] BLOCKED_BY_ANALYSIS_QUALITY"
APP_API_RAPOR_BLOCKED_BY_PDF_ASSERT_LOG_PREFIX = "[app.api_rapor] BLOCKED_BY_PDF_ASSERT"

# Log prefixes for teacher report endpoint
TEACHER_REPORT_ENDPOINT_PROACTIVE_REANALYSIS_LOG_PREFIX = "[teacher_report_endpoint] PROACTIVE_REANALYSIS_FOR_V6_3"
TEACHER_REPORT_ENDPOINT_AUTO_REANALYSIS_LOG_PREFIX = "[teacher_report_endpoint] AUTO_REANALYSIS_AFTER_CONSISTENCY_FAILURE"
TEACHER_REPORT_ENDPOINT_GOLDEN_REGRESSION_FAIL_LOG_PREFIX = "[teacher_report_endpoint] GOLDEN_REGRESSION_FAIL"
TEACHER_REPORT_ENDPOINT_RESPONSE_LOG_PREFIX = "[teacher_report_endpoint] RESPONSE"
TEACHER_REPORT_ENDPOINT_ERROR_LOG_PREFIX = "[teacher_report_endpoint] ERROR"
